//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntiies
{
    using System;using IronFramework.Utility.EntityFramewrok;
    using System.Collections.Generic;
    
    public partial class Categroy:IEntity
    {
        public Categroy()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    
        #region IEntity Members
            public State State { get; set; } 
        #endregion
          
        public virtual ICollection<Product> Product { get; set; }
    }
}
